const person = {
  theophilus: {
    name1: "ቴዎፍሎስ",
    nameE1: "Theophilus",
    nameM1: "ዓርኪ/ ፍቁር  ኣምላኽ",
    name2: "",
    nameE2: "",
    nameM2: "",
    title: "",
    adres: "",
    info: "",
  },
  luke: {
    name1: "ሉቃስ",
    nameE1: "Luke",
    nameM1: "እቲ ዝበርሀ ",
    name2: "",
    nameE2: "",
    nameM2: "",
    title: "ሓኪም፣ ጸሓፊ ወንጌል ሉቃስ",
    adres: "",
    info: "ዓሌቱ ግሪኻዊ",
  },
  barsabas: {
    name1: "ባርሳባስ",
    nameE1: "Barsabas",
    nameM1: "ወዲ ሰንበት ",
    name2: "ዬሴፍ : ዮስጦስ",
    nameE2: "Joseph Justus ",
    nameM2: "",
    title: "",
    adres: "",
    info: "",
    man: true,
  },
  matthias: {
    name1: "ማትያስ",
    nameE1: "Matthias",
    nameM1: "ህያብ ኣምላኽ ",
    name2: "",
    nameE2: " ",
    nameM2: "",
    title: "ሃዋርያ",
    adres: "",
    info: "",
    man: true,
  },
  peter: {
    name1: "ጴጥሮስ",
    nameE1: "Peter",
    nameM1: "ከውሒ",
    name2: "ስምኦን",
    nameE2: "Simon ",
    nameM2: "ንሱ ይሰምዕ እዩ",
    title: "ሃዋርያ, ገፋፊ ዓሳ",
    adres: "",
    info: "ሓዉ ንእንድርያስ： በዓል ሓዳር ",
    man: true,
  },
  john: {
    name1: "ዮሐንስ",
    nameE1: "John",
    nameM1: "",
    name2: "",
    nameE2: " ",
    nameM2: "",
    title: "ሃዋርያ",
    adres: "",
    info: "ሓዉ ንያዕቆብ",
    man: true,
  },
};
const plc = {
  jerusalem: {
    name1: "የሩሳሌም",
    nameE1: "Jerusalem",
    nameM1: "ወዲ የሩሳሌም",
    name2: "",
    nameE2: "",
    nameM2: "",
    vers: "",
    gMap: "https://maps.app.goo.gl/SwKKPFPFNv7D5ty97",
    info: "",
  },
  olivet: {
    name1: "ደብረ ዘይቲ",
    nameE1: "Olivet",
    nameM1: "",
    name2: "",
    nameE2: "",
    nameM2: "",
    vers: "",
    gMap: "https://maps.app.goo.gl/RvFHnh1ZquQzfhoC8 ",
    info: "",
  },
};
